"""
Legal Researcher Service - Legal Advice Agent
"""

import os
import logging
from datetime import datetime, UTC
from typing import Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv
from agents import Agent, Runner, trace

# Suppress LiteLLM warnings about optional dependencies
logger = logging.getLogger(__name__)
logging.getLogger("LiteLLM").setLevel(logging.CRITICAL)

# Import from our modules
from context import get_agent_instructions, DEFAULT_RESEARCH_PROMPT
from mcp_servers import create_playwright_mcp_server
from research_evaluation import (
    evaluate_research_output,
    get_research_litellm_model,
    needs_search_refinement,
    refine_research_with_serper,
)
from tools import ingest_legal_document

# Load environment
load_dotenv(override=True)

app = FastAPI(title="FinPlex Researcher Service")


# Request model
class ResearchRequest(BaseModel):
    topic: Optional[str] = None  # Optional - if not provided, agent picks a topic


async def _run_primary_research_agent(user_query: str) -> str:
    """First pass: Playwright MCP + optional ingest to legal API."""
    model = get_research_litellm_model()
    with trace("Researcher-primary"):
        async with create_playwright_mcp_server(timeout_seconds=60) as playwright_mcp:
            agent = Agent(
                name="Legal Companion Researcher",
                instructions=get_agent_instructions(),
                model=model,
                tools=[ingest_legal_document],
                mcp_servers=[playwright_mcp],
            )
            result = await Runner.run(agent, input=user_query, max_turns=15)
    return (result.final_output or "").strip()


async def run_research_agent(topic: str = None) -> str:
    """Run research: primary browse pass → evaluator → optional Serper (Google) refinement.

    1) Primary agent: Playwright-based browsing + ingest (existing behavior).
    2) Evaluator agent: returns JSON (adequate / confidence / issues / suggested queries).
    3) If refinement is needed and ``SERPER_API_KEY`` is set, a third agent uses the
       ``serper_google_search`` tool (Serper.dev) and produces an improved answer.
    If Serper is not configured, the draft is returned and a short note is appended.
    """
    if topic:
        query = f"Research this legal topic: {topic}"
    else:
        query = DEFAULT_RESEARCH_PROMPT

    model = get_research_litellm_model()
    draft = await _run_primary_research_agent(query)
    if not draft:
        return "No output was generated by the research agent."

    ev = await evaluate_research_output(query, draft, model)

    if not needs_search_refinement(ev):
        return draft

    try:
        refined = await refine_research_with_serper(query, draft, ev, model)
    except Exception as e:
        logger.exception("Serper search refinement failed: %s", e)
        refined = None

    if refined:
        return (
            f"{refined}\n\n---\n*This response was extended after an automated quality review using "
            "Google search (Serper). Not legal advice.*"
        )

    return (
        f"{draft}\n\n---\n_Automated review suggested more targeted web research, but refinement "
        "is unavailable. Set `SERPER_API_KEY` (https://serper.dev) for Google search via Serper, or "
        "re-run with a more specific topic._"
    )


@app.get("/")
async def root():
    """Health check endpoint."""
    return {
        "service": "Legal Companion Researcher",
        "status": "healthy",
        "timestamp": datetime.now(UTC).isoformat(),
    }


@app.post("/research")
async def research(request: ResearchRequest) -> str:
    """
    Generate legal research and advice.

    The agent will:
    1. Browse legal blogs and websites for data
    2. Analyze the information found
    3. Store the analysis in the knowledge base

    If no topic is provided, the agent will pick a trending topic.
    """
    try:
        return await run_research_agent(request.topic)
    except Exception as e:
        print(f"Error in research endpoint: {e}")
        import traceback

        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
async def health():
    """Detailed health check."""
    # Debug container detection
    container_indicators = {
        "dockerenv": os.path.exists("/.dockerenv"),
        "containerenv": os.path.exists("/run/.containerenv"),
        "aws_execution_env": os.environ.get("AWS_EXECUTION_ENV", ""),
        "ecs_container_metadata": os.environ.get("ECS_CONTAINER_METADATA_URI", ""),
    }

    return {
        "service": "Legal Companion Researcher",
        "status": "healthy",
        "legal_api_configured": bool(
            os.getenv("LEGAL_API_ENDPOINT") and os.getenv("LEGAL_API_KEY")
        ),
        "serper_google_search_configured": bool(
            (os.environ.get("SERPER_API_KEY") or "").strip()
        ),
        "timestamp": datetime.now(UTC).isoformat(),
        "debug_container": container_indicators,
        "aws_region": os.environ.get("AWS_DEFAULT_REGION", "not set"),
    }

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
